name: first workflow

on: [push]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello world
        run: echo Hello world
    
      - name: Multi line step1
        run: |
          pwd
          ls 
