name: first workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello world
        run: echo Hello world
    
      - name: Multi line step1
        run: |
          pwd
          ls

  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: get_step
        run: |
          echo "COUNT=$(wc -l < ./sample.sh | awk '{print $1}')" >> $GITHUB_ENV
      - name: Set outputs
        id: set_step
        run: |
          echo "::set-output name=COUNT::$(wc -l < ./sample.sh | awk '{print $1}')"
    outputs:
      COUNT: ${{ steps.set_step.outputs.COUNT }}


