name: first workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello world
        run: echo Hello world
    
      - name: Multi line step1
        run: |
          pwd
          ls

  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: get_step
        run: |
          count=$(wc -l < ./sample.sh)
          echo "Line count: $count"
          echo "COUNT=$count" >> $GITHUB_ENV
          id: count_step
    outputs:
            needs: first-job
            count: ${{ steps.get_step.outputs.COUNT }}

